name: login_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  json_annotation: ^4.8.0
  http: ^1.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/users.json
    - assets/child_logo.png
    - assets/professor_image.png
    - assets/mapa_pobles.png
    - assets/primer_trimestre.png
    - assets/segon_trimestre.png
    - assets/tercer_trimestre.png
    - assets/estat_alumnes.json
    - assets/estat_temes.json


    

  
